# sudo: required
sudo: false
dist: trusty
language: csharp
mono:
  - latest
solution: Everest.sln
env:
    global:
        - "BUILD_NUMBER=$TRAVIS_BUILD_NUMBER"
        - "BUILD_DIR=$TRAVIS_BUILD_DIR"
script:
    - chmod a+x ./replace-version.sh
    - ./replace-version.sh
    - msbuild /p:TravisCore=true /p:Configuration=Release
after_success:
    - chmod a+x ./travis-release.sh
    - ./travis-release.sh